terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.23" # Express Mode resources landed in 6.23
    }
  }

  # Remote state lives in S3 + DynamoDB locks; bootstrap via deploy/bootstrap/.
  # Backend blocks cannot interpolate variables, so concrete values are passed
  # via `-backend-config=backend.conf` (generated by the bootstrap module).
  # backend.conf is gitignored.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
}

# Use default VPC unless caller provides one. Keeps the demo runnable; for prod
# you'd want a dedicated VPC with private subnets + NAT.
data "aws_vpc" "target" {
  id      = var.vpc_id != "" ? var.vpc_id : null
  default = var.vpc_id == "" ? true : null
}

data "aws_subnets" "target" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.target.id]
  }
}

data "aws_caller_identity" "current" {}

locals {
  name_prefix = var.project_name
  account_id  = data.aws_caller_identity.current.account_id
}

# ─── Remote-state resources (created by deploy/bootstrap/) ─────────────
# Looked up here so IAM policies can reference their real ARNs.
# If these data lookups fail, run `terraform apply` in deploy/bootstrap/ first.
data "aws_s3_bucket" "state" {
  bucket = "${var.project_name}-tfstate-${local.account_id}"
}

data "aws_dynamodb_table" "lock" {
  name = "${var.project_name}-tflock"
}

data "aws_kms_alias" "state" {
  name = "alias/${var.project_name}-tfstate"
}
